name: Deploy my protfolio to S3
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.S3_BUCKET_REGION }}

    - name: Deploy static site to S3 bucket
      run: | 
        ls
        aws s3 sync index.html s3://${{ secrets.S3_BUCKET }}/index.html --delete
        aws s3 sync Resume.pdf s3://${{ secrets.S3_BUCKET }}/Resume.pdf --delete
        aws s3 sync css/* s3://${{ secrets.S3_BUCKET }}/css/* --delete
        aws s3 sync js/* s3://${{ secrets.S3_BUCKET }}/js/* --delete
        aws s3 sync Images/* s3://${{ secrets.S3_BUCKET }}/Images/* --delete